import * as crypto from 'crypto';

export interface VoiceConsentRecord {
  voiceId: string;
  speakerName: string;
  consentTimestamp: string;
  permittedUsage: 'personal_assistant' | 'narration' | 'commercial_dubbing';
  consentSignature: string;
}

export interface SyntheticMediaDisclosure {
  generatedBy: string;
  capabilityId: string;
  modelIdentifier: string;
  isSynthetic: boolean;
  disclosureTag: string;
  sha256Watermark: string;
}

export class MediaConsentGuard {
  private voiceConsents = new Map<string, VoiceConsentRecord>();

  public registerVoiceConsent(
    voiceId: string,
    speakerName: string,
    permittedUsage: 'personal_assistant' | 'narration' | 'commercial_dubbing'
  ): VoiceConsentRecord {
    const consentTimestamp = new Date().toISOString();
    const sig = crypto
      .createHash('sha256')
      .update(`${voiceId}:${speakerName}:${permittedUsage}:${consentTimestamp}`)
      .digest('hex');

    const record: VoiceConsentRecord = {
      voiceId,
      speakerName,
      consentTimestamp,
      permittedUsage,
      consentSignature: sig
    };

    this.voiceConsents.set(voiceId, record);
    return record;
  }

  public verifyVoiceConsent(voiceId: string, intendedUsage: 'personal_assistant' | 'narration' | 'commercial_dubbing'): {
    isAllowed: boolean;
    reason?: string;
  } {
    const record = this.voiceConsents.get(voiceId);
    if (!record) {
      return {
        isAllowed: false,
        reason: `No documented voice consent found for voice ID: ${voiceId}`
      };
    }

    if (record.permittedUsage !== intendedUsage && record.permittedUsage !== 'commercial_dubbing') {
      return {
        isAllowed: false,
        reason: `Voice consent permitted for ${record.permittedUsage}, but requested usage is ${intendedUsage}`
      };
    }

    return { isAllowed: true };
  }

  public generateSyntheticDisclosure(
    capabilityId: string,
    modelIdentifier: string,
    outputBufferOrText: Buffer | string
  ): SyntheticMediaDisclosure {
    const buffer = Buffer.isBuffer(outputBufferOrText)
      ? outputBufferOrText
      : Buffer.from(outputBufferOrText, 'utf-8');

    const watermark = crypto.createHash('sha256').update(buffer).digest('hex');

    return {
      generatedBy: 'AI Chatbot Hub',
      capabilityId,
      modelIdentifier,
      isSynthetic: true,
      disclosureTag: `Synthetic Media Generated by AI Chatbot Hub (${capabilityId}) using ${modelIdentifier}`,
      sha256Watermark: watermark
    };
  }
}
