/**
 * Source Code File Filter & Generated Code Classifier
 * (CRK Phase 14: CRK-P14-T02, T03, T08)
 */

import { WhitelistedLanguage, FileFilterResult } from '../../types/source-code-pack';

export class SourceCodeFileFilter {
  private static readonly EXTENSION_MAP: Record<string, WhitelistedLanguage> = {
    '.ts': 'typescript',
    '.tsx': 'typescript',
    '.js': 'javascript',
    '.jsx': 'javascript',
    '.py': 'python',
    '.rs': 'rust',
    '.go': 'go',
    '.c': 'c',
    '.h': 'c',
    '.cpp': 'cpp',
    '.hpp': 'cpp',
    '.cs': 'csharp',
    '.java': 'java',
    '.lua': 'lua',
    '.gd': 'gdscript',
    '.sql': 'sql',
    '.sh': 'shell',
    '.bash': 'shell',
    '.ps1': 'powershell',
    '.html': 'html',
    '.htm': 'html',
    '.css': 'css',
    '.dockerfile': 'dockerfile',
    '.cmake': 'cmake',
  };

  private static readonly EXCLUDED_DIR_PATTERNS = [
    /(?:^|[\\/])(?:node_modules|vendor|dist|build|coverage|\.git|\.next|out|target)[\\/]/i,
  ];

  private static readonly EXCLUDED_FILE_PATTERNS = [
    /\.min\.(js|css)$/i,
    /\.bundle\.(js|css)$/i,
    /\.(map|lock|lockb|sum|snap)$/i,
    /^(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Cargo\.lock|composer\.lock)$/i,
  ];

  private static readonly GENERATED_HEADERS = [
    /@generated/i,
    /auto-?generated/i,
    /code generated by .* do not edit/i,
    /this file is generated/i,
    /sourceMappingURL=/i,
  ];

  public detectLanguage(filePath: string): WhitelistedLanguage | undefined {
    const lowerPath = filePath.toLowerCase();
    if (lowerPath.endsWith('dockerfile')) return 'dockerfile';
    if (lowerPath.endsWith('cmakelists.txt')) return 'cmake';

    const match = lowerPath.match(/\.[a-z0-9]+$/i);
    if (!match) return undefined;
    return SourceCodeFileFilter.EXTENSION_MAP[match[0]];
  }

  public filter(filePath: string, content: string): FileFilterResult {
    // 1. Check directory exclusions
    for (const pattern of SourceCodeFileFilter.EXCLUDED_DIR_PATTERNS) {
      if (pattern.test(filePath)) {
        return { accepted: false, reason: `Path matches excluded directory pattern: ${filePath}` };
      }
    }

    // 2. Check filename exclusions
    const filename = filePath.split(/[\\/]/).pop() || '';
    for (const pattern of SourceCodeFileFilter.EXCLUDED_FILE_PATTERNS) {
      if (pattern.test(filename)) {
        return { accepted: false, reason: `Excluded lock, bundle, or snapshot file: ${filename}` };
      }
    }

    // 3. Language whitelist check
    const language = this.detectLanguage(filePath);
    if (!language) {
      return { accepted: false, reason: `File language not in whitelist: ${filePath}` };
    }

    // 4. Generated-code classifier check
    const headerSlice = content.slice(0, 1000);
    for (const pattern of SourceCodeFileFilter.GENERATED_HEADERS) {
      if (pattern.test(headerSlice)) {
        return {
          accepted: false,
          isGenerated: true,
          reason: `Detected generated code header in ${filePath}`,
          detectedLanguage: language,
        };
      }
    }

    // 5. Check for minification heuristics (e.g., average line length > 300)
    const lines = content.split('\n');
    if (lines.length > 0 && content.length > 500) {
      const avgLineLength = content.length / lines.length;
      if (avgLineLength > 250) {
        return {
          accepted: false,
          isGenerated: true,
          reason: `Detected minified source code (average line length ${Math.round(avgLineLength)})`,
          detectedLanguage: language,
        };
      }
    }

    return {
      accepted: true,
      detectedLanguage: language,
    };
  }
}
