export type ChatMode =
  | 'ask'
  | 'plan'
  | 'implement'
  | 'debug'
  | 'explain'
  | 'coding'
  | 'gaming'
  | 'gamedev'
  | 'pop_culture'
  | 'history'
  | 'science'
  | 'music'
  | 'suno'
  | 'fl_studio'
  | 'fl_studio_control'
  | 'pro_tools'
  | 'logic'
  | 'mix_master'
  | 'story'
  | 'creative_writing'
  | 'roleplay'
  | 'legal'
  | 'health'
  | 'security'
  | 'business'
  | 'philosophy'
  | 'language'
  | 'geography'
  | 'engineering'
  | 'knowledge_os';

export type UserIntent = 'ask' | 'plan' | 'implement' | 'debug' | 'explain';
