export type RuntimeProfile = 'development' | 'test' | 'local' | 'hosted';
export type EnvironmentRequirement = 'required' | 'optional' | 'deprecated' | 'local-only';

export interface EnvironmentDefinition {
  name: string;
  category: string;
  requirement: EnvironmentRequirement;
  description: string;
  secret?: boolean;
  defaultValue?: string;
  deprecatedBy?: string;
}

const optional = (name: string, category: string, description: string, defaultValue?: string): EnvironmentDefinition => ({
  name, category, requirement: 'optional', description, defaultValue
});
const secret = (name: string, category: string, description: string): EnvironmentDefinition => ({
  name, category, requirement: 'optional', description, secret: true
});
const localOnly = (name: string, category: string, description: string, defaultValue?: string): EnvironmentDefinition => ({
  name, category, requirement: 'local-only', description, defaultValue
});
const deprecated = (name: string, category: string, description: string, deprecatedBy: string): EnvironmentDefinition => ({
  name, category, requirement: 'deprecated', description, deprecatedBy
});

export const ENVIRONMENT_DEFINITIONS: EnvironmentDefinition[] = [
  optional('NODE_ENV', 'runtime', 'Node runtime environment.', 'development'),
  optional('DEPLOYMENT_MODE', 'runtime', 'Runtime profile: development, test, local, or hosted.'),
  optional('PORT', 'runtime', 'HTTP listen port.', '3001'),
  optional('BASE_URL', 'runtime', 'Canonical externally visible application URL.'),
  optional('STARTUP_TIMEOUT_MS', 'runtime', 'Maximum service initialization wait.', '30000'),
  optional('REQUEST_READY_TIMEOUT_MS', 'runtime', 'Maximum request readiness wait.', '10000'),
  secret('JWT_SECRET', 'security', 'JWT signing secret; required and strong outside tests.'),
  secret('CSRF_TOKEN', 'security', 'Static CSRF token for deployments that use the configured token policy.'),
  optional('CORS_ORIGIN', 'security', 'Exact allowed browser origin.', 'http://localhost:3000'),
  optional('CORS_CREDENTIALS', 'security', 'Whether credentialed CORS is enabled.', 'true'),
  secret('API_KEY_ENCRYPTION_SECRET', 'security', 'Dedicated key-encryption secret for stored provider credentials.'),
  optional('TRUST_PROXY', 'security', 'Express trusted proxy setting.', 'false'),
  optional('RATE_LIMIT_WINDOW_MS', 'security', 'Rate-limit window in milliseconds.', '60000'),
  optional('RATE_LIMIT_MAX_REQUESTS', 'security', 'Default requests allowed per window.', '100'),
  optional('LOG_LEVEL', 'observability', 'Application log level.', 'info'),
  optional('LLM_PROVIDER', 'providers', 'Primary LLM provider identifier.', 'template'),
  optional('USE_OLLAMA', 'providers', 'Enable Ollama provider.', 'false'),
  optional('OLLAMA_URL', 'providers', 'Ollama API URL.', 'http://localhost:11434'),
  optional('OLLAMA_MODEL', 'providers', 'Ollama model name.', 'llama2'),
  optional('USE_HUGGINGFACE', 'providers', 'Enable Hugging Face provider.', 'false'),
  optional('HUGGINGFACE_MODEL', 'providers', 'Hugging Face model identifier.'),
  secret('HUGGINGFACE_API_KEY', 'providers', 'Hugging Face API token.'),
  secret('OPENAI_API_KEY', 'providers', 'OpenAI API key.'),
  optional('OPENAI_MODEL', 'providers', 'OpenAI chat model.'),
  secret('OPENAI_COMPATIBLE_API_KEY', 'providers', 'OpenAI-compatible provider key.'),
  optional('OPENAI_COMPATIBLE_BASE_URL', 'providers', 'OpenAI-compatible provider base URL.'),
  optional('OPENAI_COMPATIBLE_MODEL', 'providers', 'OpenAI-compatible provider model.'),
  optional('OPENAI_COMPATIBLE_PROVIDER_NAME', 'providers', 'Display name for an OpenAI-compatible provider.'),
  secret('ANTHROPIC_API_KEY', 'providers', 'Anthropic API key.'),
  optional('ANTHROPIC_MODEL', 'providers', 'Anthropic model name.'),
  secret('GEMINI_API_KEY', 'providers', 'Google Gemini API key.'),
  optional('GEMINI_MODEL', 'providers', 'Google Gemini model name.'),
  optional('MAX_COST_PER_REQUEST', 'providers', 'Maximum estimated provider cost per request.', '0.10'),
  optional('MAX_LATENCY_MS', 'providers', 'Preferred provider latency ceiling.', '5000'),
  optional('MAX_RETRIES', 'providers', 'Maximum provider retries.', '3'),
  localOnly('LOCAL_MODEL_ENABLED', 'providers', 'Enable external local model endpoint adapter (CF-04).', 'false'),
  localOnly('LOCAL_MODEL_BASE_URL', 'providers', 'Base URL for external local model endpoint (e.g. Warpdrv, llama.cpp, Ollama).', 'http://127.0.0.1:8080/v1'),
  localOnly('LOCAL_MODEL_PROVIDER_NAME', 'providers', 'Provider identifier for external local model endpoint.', 'warpdrv'),
  secret('LOCAL_MODEL_API_KEY', 'providers-and-integrations', 'API key for external local model endpoint if required.'),
  localOnly('LOCAL_MODEL_ALLOWLIST', 'security', 'Comma-separated IP or hostname allowlist for local model endpoints.', '127.0.0.1,localhost,::1'),
  localOnly('LOCAL_MODEL_MAX_CONCURRENCY', 'providers', 'Maximum concurrent requests to local model endpoint.', '2'),
  localOnly('LOCAL_MODEL_MAX_QUEUE_DEPTH', 'providers', 'Maximum queue depth for local model endpoint.', '8'),
  localOnly('LOCAL_MODEL_TIMEOUT_MS', 'providers', 'Timeout in milliseconds for local model requests.', '60000'),
  localOnly('LOCAL_MODEL_ROUTING_PRIVACY_MODE', 'providers', 'Privacy routing mode: strict_local, prefer_local, cloud_allowed, or local_disabled.', 'prefer_local'),
  optional('CF_ACCESSIBILITY_CERTIFIED', 'governance', 'Reviewed evidence flag for manual Capability Hub keyboard and screen-reader certification.', 'false'),
  optional('CF_RELEASE_CERTIFIED', 'governance', 'Reviewed evidence flag for the signed capability release-candidate certification.', 'false'),
  optional('EMBEDDING_PROVIDER', 'rag', 'Embedding provider: openai, xenova, or ollama.', 'xenova'),
  optional('EMBEDDING_MODEL', 'rag', 'Embedding model identifier.', 'Xenova/all-MiniLM-L6-v2'),
  optional('EMBEDDING_USE_TRANSFORMERS', 'rag', 'Enable local Transformers.js embeddings.', 'false'),
  optional('ENABLE_RAG', 'rag', 'Enable retrieval-augmented generation.', 'true'),
  optional('RAG_PERSISTENCE', 'rag', 'Persist RAG data.', 'true'),
  optional('RAG_SQLITE_PATH', 'rag', 'SQLite database path for local mode.', './data/chatbot.db'),
  optional('RAG_DATABASE_URL', 'rag', 'PostgreSQL URL for RAG persistence.'),
  optional('DATABASE_URL', 'data', 'Primary PostgreSQL URL.'),
  optional('RAG_RETRIEVAL_MODE', 'rag', 'Retrieval mode: memory, database, or hybrid.', 'memory'),
  optional('RAG_TOP_K', 'rag', 'Maximum retrieved chunks.', '10'),
  optional('RAG_SIMILARITY_THRESHOLD', 'rag', 'Minimum retrieval similarity.', '0.7'),
  optional('RAG_GENERATE_EMBEDDINGS', 'rag', 'Generate embeddings while ingesting.', 'true'),
  optional('RAG_CHUNK_SIZE', 'rag', 'Target chunk size.', '500'),
  optional('RAG_BACKUP_DIR', 'rag', 'Directory for RAG database backups.'),
  optional('RAG_EMBEDDING_BATCH_SIZE', 'rag', 'Embedding batch size for RAG persistence.'),
  optional('RAG_PERSISTENCE_BATCH_SIZE', 'rag', 'Persistence batch size for RAG writes.'),
  optional('RAG_RESTORE_PERSISTED_TO_MEMORY', 'rag', 'Restore persisted RAG records into memory at startup.'),
  optional('RAG_SQLITE_CANDIDATE_BATCH_SIZE', 'rag', 'SQLite candidate batch size.'),
  optional('RAG_SQLITE_FTS_TOKEN_LIMIT', 'rag', 'SQLite full-text-search token limit.'),
  optional('RAG_SQLITE_FULL_VECTOR_SCAN', 'rag', 'Allow full SQLite vector scans.'),
  optional('RAG_SQLITE_KEYWORD_CANDIDATES', 'rag', 'SQLite keyword candidate limit.'),
  optional('RAG_SQLITE_VECTOR_SCAN_PAGE_SIZE', 'rag', 'SQLite vector scan page size.'),
  optional('BACKGROUND_KNOWLEDGE_LOAD', 'knowledge', 'Load background knowledge asynchronously.'),
  optional('BACKGROUND_CODING_KNOWLEDGE_LOAD', 'knowledge', 'Load coding knowledge asynchronously.'),
  optional('BOOKS_CHUNK_OVERLAP', 'knowledge', 'Book-ingestion chunk overlap.'),
  optional('BOOKS_CHUNK_SIZE', 'knowledge', 'Book-ingestion chunk size.'),
  optional('BOOKS_COLLECTION', 'knowledge', 'Book-ingestion collection name.'),
  localOnly('BOOKS_DIR', 'knowledge', 'Book source directory.'),
  optional('BOOKS_EMBEDDING_BATCH_SIZE', 'knowledge', 'Book-ingestion embedding batch size.'),
  optional('BOOKS_GENERATE_EMBEDDINGS', 'knowledge', 'Generate embeddings while importing books.'),
  optional('BOOKS_PERSISTENCE_BATCH_SIZE', 'knowledge', 'Book-ingestion persistence batch size.'),
  optional('BOOKS_SOURCE_TYPE', 'knowledge', 'Book-ingestion source type.'),
  optional('BOOKS_VISIBILITY', 'knowledge', 'Book-ingestion visibility.'),
  optional('OCR_QUEUE_LIMIT', 'knowledge', 'Maximum OCR queue size.'),
  optional('OCR_REIMPORT_EMBEDDINGS', 'knowledge', 'Regenerate embeddings during OCR reimport.'),
  optional('PDF_OCR_DPI', 'knowledge', 'PDF OCR rendering DPI.'),
  optional('PDF_OCR_ENABLED', 'knowledge', 'Enable PDF OCR.'),
  optional('PDF_OCR_LANGUAGE', 'knowledge', 'PDF OCR language.'),
  optional('PDF_OCR_MAX_PAGES', 'knowledge', 'Maximum PDF pages processed by OCR.'),
  optional('KNOWLEDGE_BASE_DIR', 'rag', 'Knowledge corpus root.', './knowledge-base'),
  optional('EAGER_KNOWLEDGE_LOAD', 'rag', 'Load the general corpus during startup.', 'false'),
  optional('EAGER_CODING_KNOWLEDGE_LOAD', 'rag', 'Load coding corpus during startup.', 'false'),
  optional('GROUNDING_MODE', 'rag', 'Grounding enforcement mode.', 'off'),
  optional('GROUNDING_REQUIRED_COVERAGE', 'rag', 'Minimum citation coverage.', '0.8'),
  optional('RERANKER_MODE', 'rag', 'Reranker implementation.', 'heuristic'),
  optional('SQLITE_BUSY_TIMEOUT_MS', 'data', 'SQLite busy timeout in milliseconds.', '30000'),
  optional('AUDIO_SEARCH_MAX_FILES', 'local-tools', 'Maximum files scanned by audio search.'),
  optional('ENABLE_REDIS_CACHE', 'cache', 'Enable Redis cache.', 'false'),
  optional('REDIS_URL', 'cache', 'Redis connection URL.', 'redis://localhost:6379'),
  optional('ENABLE_DISK_CACHE', 'cache', 'Enable local disk cache.', 'true'),
  optional('DISK_CACHE_DIR', 'cache', 'Disk cache directory.', './cache'),
  optional('SEMANTIC_CACHE_TTL', 'cache', 'Semantic-cache TTL seconds.', '3600'),
  optional('SEMANTIC_CACHE_SIMILARITY_THRESHOLD', 'cache', 'Semantic-cache similarity threshold.', '0.7'),
  optional('ENABLE_CONTRACTS', 'features', 'Enable contract validation.', 'true'),
  optional('ENABLE_MEMORY', 'features', 'Enable memory features.', 'true'),
  optional('ENABLE_PROVENANCE', 'features', 'Enable provenance tracking.', 'true'),
  optional('ENABLE_CACHING', 'features', 'Enable application caching.', 'true'),
  optional('ENABLE_MODEL_ROUTING', 'features', 'Enable model routing.', 'true'),
  deprecated('MODEL_ROUTING_ENABLED', 'features', 'Legacy model-routing flag.', 'ENABLE_MODEL_ROUTING'),
  optional('ENABLE_ENSEMBLE', 'features', 'Enable ensemble responses.', 'false'),
  deprecated('ENSEMBLE_ENABLED', 'features', 'Legacy ensemble flag.', 'ENABLE_ENSEMBLE'),
  optional('ENABLE_SAFETY_PIPELINE', 'features', 'Enable response safety pipeline.', 'true'),
  optional('ENABLE_SEMANTIC_CACHE', 'features', 'Enable semantic cache.', 'true'),
  optional('ENABLE_WEBSOCKET', 'features', 'Enable WebSocket server.', 'true'),
  optional('ENABLE_TOOL_CALLING', 'features', 'Enable model tool calls.', 'true'),
  localOnly('ENABLE_BASH_EXECUTOR', 'local-tools', 'Enable direct bash execution.', 'false'),
  localOnly('ENABLE_CODE_EXECUTOR', 'local-tools', 'Enable code execution only with a separately provisioned sandbox.', 'false'),
  localOnly('CODE_EXECUTOR_SANDBOX', 'local-tools', 'Assert that the host supplied a real isolated code-execution sandbox.', 'false'),
  optional('CODING_MODEL_CONTEXT_TOKENS', 'features', 'Model context capacity used by adaptive coding context allocation.', '12000'),
  localOnly('CODING_EVAL_MODEL', 'local-tools', 'Optional model identifier for explicitly authorized live coding benchmark runs.'),
  localOnly('CODING_EVAL_PROVIDER', 'local-tools', 'Provider selector for explicitly authorized live coding benchmark runs.'),
  localOnly('CODING_MODEL_MAX_OUTPUT_TOKENS', 'local-tools', 'Maximum model output tokens for coding drafts.'),
  localOnly('ENABLE_LOCAL_TOOLS', 'local-tools', 'Enable local-tool routes and services.', 'false'),
  localOnly('LOCAL_EXECUTION_ENABLED', 'local-tools', 'Master local execution switch.', 'false'),
  localOnly('LOCAL_TOOLS_DIR', 'local-tools', 'Local tool bundle directory.', './local-tools'),
  localOnly('PRIVATE_TOOL_BUNDLES_DIR', 'local-tools', 'Private local tool bundle directory.', './data/tools/private-bundles'),
  localOnly('SPRITE_LAB_DIR', 'local-tools', 'Sprite Lab workspace directory.', './data/sprite-lab'),
  localOnly('AUDIO_LAB_DIR', 'local-tools', 'Audio workspace directory.', './data/audio-lab'),
  localOnly('ENABLE_FL_STUDIO_MCP', 'local-tools', 'Enable FL Studio MCP bridge.', 'false'),
  optional('PYSCRAPPY_ENABLED', 'research', 'Enable the optional PyScrappy MCP research bridge.'),
  optional('PYSCRAPPY_MCP_COMMAND', 'research', 'PyScrappy MCP executable.'),
  optional('PYSCRAPPY_MCP_ARGS', 'research', 'JSON arguments passed to PyScrappy MCP.'),
  optional('PYSCRAPPY_MCP_CWD', 'research', 'Working directory for PyScrappy MCP.'),
  optional('PYSCRAPPY_SCRAPE_TOOL', 'research', 'PyScrappy MCP scrape tool name.'),
  optional('PYSCRAPPY_MAX_OUTPUT_BYTES', 'research', 'Maximum PyScrappy output size.'),
  optional('USE_LLAVA', 'vision', 'Enable LLaVA through Ollama.', 'false'),
  optional('LLAVA_MODEL', 'vision', 'LLaVA model name.', 'llava'),
  optional('USE_GEMINI_VISION', 'vision', 'Enable Gemini vision.', 'false'),
  optional('USE_GPT4V', 'vision', 'Enable OpenAI vision.', 'false'),
  optional('SEC_USER_AGENT', 'integrations', 'SEC fair-access user agent.'),
  optional('SEC_DATA_DIR', 'integrations', 'SEC data directory.', './data/sec'),
  optional('SEC_MAX_REQUESTS_PER_SECOND', 'integrations', 'SEC request pacing.', '8'),
  secret('GITHUB_TOKEN', 'integrations', 'GitHub API token for optional knowledge ingestion.'),
  secret('YOUTUBE_API_KEY', 'integrations', 'YouTube API key.'),
  secret('STACKOVERFLOW_API_KEY', 'integrations', 'Stack Overflow API key.'),
  secret('NEWS_API_KEY', 'integrations', 'News API key.'),
  secret('GUARDIAN_API_KEY', 'integrations', 'Guardian API key.'),
  secret('NYTIMES_API_KEY', 'integrations', 'New York Times API key.'),
  secret('TMDB_API_KEY', 'integrations', 'TMDB API key.'),
  secret('FRED_API_KEY', 'integrations', 'FRED API key.'),
  secret('TWILIO_ACCOUNT_SID', 'notifications', 'Twilio account SID.'),
  secret('TWILIO_AUTH_TOKEN', 'notifications', 'Twilio auth token.'),
  optional('TWILIO_FROM_NUMBER', 'notifications', 'Twilio sending phone number.'),
  optional('SAFETY_CHECK_FACTS', 'safety', 'Enable factual safety checks.', 'true'),
  optional('SAFETY_CONFIDENCE_THRESHOLD', 'safety', 'Safety confidence threshold.', '0.7'),
  optional('ALLOW_PRIVATE_WEBHOOK_URLS', 'security', 'Permit explicitly configured private-network webhook targets in trusted local environments.'),
  secret('ASSEMBLYAI_API_KEY', 'providers-and-integrations', 'Assemblyai api key.'),
  secret('BING_API_KEY', 'providers-and-integrations', 'Bing api key.'),
  localOnly('BLACKBELT_SOURCE_DIR', 'local-tools', 'Blackbelt source dir.'),
  secret('BRANCH_PROTECTION_TOKEN', 'providers-and-integrations', 'Administrative GitHub token used only by the branch-protection helper.'),
  secret('CARTESIA_API_KEY', 'providers-and-integrations', 'Cartesia api key.'),
  secret('CEREBRAS_API_KEY', 'providers-and-integrations', 'Cerebras api key.'),
  optional('CEREBRAS_MODEL', 'providers', 'Cerebras model.'),
  optional('CLAUDE_MODEL', 'providers', 'Claude model.'),
  localOnly('CODE_EXECUTOR_TIMEOUT', 'local-tools', 'Code executor timeout.'),
  secret('COHERE_API_KEY', 'providers-and-integrations', 'Cohere api key.'),
  optional('COHERE_MODEL', 'providers', 'Cohere model.'),
  secret('COMICVINE_API_KEY', 'providers-and-integrations', 'Comicvine api key.'),
  optional('CUDA_VISIBLE_DEVICES', 'build-and-system', 'Cuda visible devices.'),
  optional('DEBUG_MODE', 'build-and-system', 'Debug mode.'),
  secret('DEEPSEEK_API_KEY', 'providers-and-integrations', 'Deepseek api key.'),
  optional('DEEPSEEK_MODEL', 'providers', 'Deepseek model.'),
  secret('ELEVENLABS_API_KEY', 'providers-and-integrations', 'Elevenlabs api key.'),
  localOnly('ENABLE_AGENT_PATCH_APPLY', 'local-tools', 'Allow approved local agent patches to be applied.'),
  optional('ENABLE_FILE_LOGGING', 'integrations', 'Enable file logging.'),
  secret('EUROPEANA_API_KEY', 'providers-and-integrations', 'Europeana api key.'),
  optional('EVAL_TARGET_URL', 'build-and-system', 'Eval target url.'),
  localOnly('FILE_SEARCH_MAX_CONTENT_BYTES', 'local-tools', 'File search max content bytes.'),
  localOnly('FILE_SEARCH_MAX_FILES', 'local-tools', 'File search max files.'),
  localOnly('FL_STUDIO_MCP_ARGS', 'local-tools', 'Fl studio mcp args.'),
  localOnly('FL_STUDIO_MCP_COMMAND', 'local-tools', 'Fl studio mcp command.'),
  localOnly('FL_STUDIO_MCP_CWD', 'local-tools', 'Fl studio mcp cwd.'),
  optional('GENERAL_CORPUS_DELAY_MS', 'knowledge', 'General corpus delay ms.'),
  optional('GENERAL_CORPUS_LIMIT', 'knowledge', 'General corpus limit.'),
  optional('GENERAL_CORPUS_RETRIES', 'knowledge', 'General corpus retries.'),
  optional('GENERAL_CORPUS_RETRY_DELAY_MS', 'knowledge', 'General corpus retry delay ms.'),
  optional('GENERAL_CORPUS_TOPICS', 'knowledge', 'General corpus topics.'),
  optional('GENERAL_CORPUS_YEAR_EVENTS', 'knowledge', 'General corpus year events.'),
  optional('GIS_ARCGIS_PARCEL_LAYER_URL', 'gis', 'Gis arcgis parcel layer url.'),
  optional('GIS_DEFAULT_CENTER_LAT', 'gis', 'Gis default center lat.'),
  optional('GIS_DEFAULT_CENTER_LNG', 'gis', 'Gis default center lng.'),
  optional('GIS_GEOCODER_PROVIDER', 'gis', 'Gis geocoder provider.'),
  optional('GIS_PARCEL_PROVIDER', 'gis', 'Gis parcel provider.'),
  optional('GIS_PROVIDER_CACHE_TTL_SECONDS', 'gis', 'Gis provider cache ttl seconds.'),
  optional('GIS_REDACT_EXACT_ADDRESSES', 'gis', 'Gis redact exact addresses.'),
  optional('GIS_ROUTING_PROVIDER', 'gis', 'Gis routing provider.'),
  optional('GITHUB_BRANCH', 'build-and-system', 'Github branch.'),
  optional('GITHUB_PAGES', 'build-and-system', 'Github pages.'),
  optional('GITHUB_REPOSITORY', 'build-and-system', 'Github repository.'),
  secret('GOOGLE_API_KEY', 'providers-and-integrations', 'Google api key.'),
  secret('GOOGLE_BOOKS_API_KEY', 'providers-and-integrations', 'Google books api key.'),
  optional('GOOGLE_CSE_ID', 'integrations', 'Google cse id.'),
  optional('GPT4V_MODEL', 'providers', 'Gpt4v model.'),
  optional('GPU_AVAILABLE', 'build-and-system', 'Gpu available.'),
  optional('GPU_MEMORY_MB', 'build-and-system', 'Gpu memory mb.'),
  secret('GROQ_API_KEY', 'providers-and-integrations', 'Groq api key.'),
  optional('GROQ_MODEL', 'providers', 'Groq model.'),
  optional('KNOWLEDGE_GRAPH_MAX_FILES', 'knowledge', 'Knowledge graph max files.'),
  localOnly('LOCAL_KNOWLEDGE_WIKI_DIR', 'knowledge', 'Local knowledge wiki dir.'),
  localOnly('LOGS_DIR', 'local-tools', 'Logs dir.'),
  optional('NODE_OPTIONS', 'build-and-system', 'Node.js runtime options; inherited or supplied by CI.'),
  optional('NVIDIA_VISIBLE_DEVICES', 'build-and-system', 'Nvidia visible devices.'),
  secret('OMDB_API_KEY', 'providers-and-integrations', 'Omdb api key.'),
  secret('OPENROUTER_API_KEY', 'providers-and-integrations', 'Openrouter api key.'),
  optional('OPENROUTER_MODEL', 'providers', 'Openrouter model.'),
  optional('OSRM_BASE_URL', 'gis', 'Osrm base url.'),
  optional('PATH', 'build-and-system', 'Operating-system executable search path; inherited rather than normally set in .env.'),
  localOnly('PIXELORAMA_CLI_ARGS_JSON', 'local-tools', 'Pixelorama cli args json.'),
  secret('POLYGON_API_KEY', 'providers-and-integrations', 'Polygon api key.'),
  optional('POSTGRES_VECTOR_TEST_URL', 'build-and-system', 'Postgres vector test url.'),
  localOnly('PUBLIC_KNOWLEDGE_BASE_DIR', 'knowledge', 'Public knowledge base dir.'),
  optional('RATE_LIMIT_FAIL_OPEN', 'security', 'Allow low-risk routes to continue when shared rate-limit storage is unavailable.'),
  localOnly('RUN_FL_STUDIO_MCP_BRIDGE_TEST', 'local-tools', 'Run fl studio mcp bridge test.'),
  secret('SEARCH_API_KEY', 'providers-and-integrations', 'Search api key.'),
  optional('SEARCH_ENGINE', 'integrations', 'Search engine.'),
  optional('SEC_QUEUE_MAX_ITEMS', 'integrations', 'Sec queue max items.'),
  secret('SIXSIGMA_ANALYSIS_API_KEY', 'providers-and-integrations', 'Sixsigma analysis api key.'),
  localOnly('SIXSIGMA_ANALYSIS_API_URL', 'local-tools', 'Sixsigma analysis api url.'),
  secret('SMITHSONIAN_API_KEY', 'providers-and-integrations', 'Smithsonian api key.'),
  optional('TEMP', 'build-and-system', 'Operating-system temporary directory; inherited rather than normally set in .env.'),
  optional('USERPROFILE', 'build-and-system', 'Windows user profile directory; inherited rather than normally set in .env.'),
  optional('VITE_PUBLIC_API_BASE_URL', 'build-and-system', 'Client-visible API base URL injected by Vite.'),
  optional('VITE_RUNTIME_MODE', 'build-and-system', 'Client runtime profile injected by Vite.'),
  optional('WIKIPEDIA_API_BASE', 'knowledge', 'Wikipedia API base URL.'),
];

export const ENVIRONMENT_DEFINITION_MAP = new Map(
  ENVIRONMENT_DEFINITIONS.map(definition => [definition.name, definition])
);

export function resolveDeploymentMode(env: NodeJS.ProcessEnv = process.env): RuntimeProfile {
  const explicit = env.DEPLOYMENT_MODE;
  if (explicit === 'development' || explicit === 'test' || explicit === 'local' || explicit === 'hosted') return explicit;
  if (env.NODE_ENV === 'test') return 'test';
  if (env.NODE_ENV === 'production') return 'hosted';
  return 'development';
}

export function isHostedMode(env: NodeJS.ProcessEnv = process.env): boolean {
  return resolveDeploymentMode(env) === 'hosted';
}
